### ISSUE TITLE
Healthcheck should attempt to fix itself

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/next-syndication-api#68]
The ["Syndication database data integrity"](https://healthcheck.ft.com/service/b5c57bcd5df76fee46a1eaf1bccabaf1/a9d04311fae756528531a91365bfb32e) healthcheck tends to go off relatively often, the fix has generally been exactly what’s in the panic guide (run `select syndication.reload_all();`)

It’d be great if the endpoint tried to fix itself before alerting which would likely mean a larger issue

**Comment by bjfletcher** [comment]
@leggsimon pointed me to another health check that does self healing stuff: https://github.com/Financial-Times/next-es-interface/blob/master/server/checks/in-sync.js
