### ISSUE TITLE
Link in README doesn't work

### ISSUE THREAD

**Issue by jkerr321** [Financial-Times/next-syndication-api#86]
...and it shouldn't be there anyway. But in that case, what should the instructions be?

The link in question is: `Use this link to get set up on the complimentary access licence: join.ft.com/4ec865b6-a757-4869-ad0c-e80807c82989`. A link to a free access licence shouldn't be shared on a public repo, and the token on that link has expired anyway, but not sure what the README should suggest in it's place?

**Comment by alicebartlett** [comment]
This method for getting added to contracts has now been shut down and the instructions for getting added to a SF contract have been updated. #92
